### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by terapi09** [gnosis/cowswap#1298]
**Steps**:
1. Open the app 
2. Press on the built-in browser's translate option 
3. Swap tokens

**AR**: the app is crashed
![image](https://user-images.githubusercontent.com/70885163/131637947-e7201d2a-486f-4be7-9974-662c0cf489d3.png)

## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": ""
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "10",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ks (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2497570)
    at Pu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2509382)
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2507340)
    at mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2503426)
    at https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452580
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Gi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452525)
    at Ji (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452460)
    at je (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2523809)
    at Qt (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2431084)
    at HTMLDivElement.r (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:4212159)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; VIA_A3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.159",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.159"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "model": "VIA_A3",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by W3stside** [comment]
I believe this is a missing `key` prop issue and/or something with the cow game. the info here doesn't match with the bug. It's not a state issue it's an unmounting component that has children that is incorrectly being unmounted. but without seeing the development stack trace I have no idea which.

**Comment by alfetopito** [comment]
Duplicated by #https://github.com/gnosis/cowswap/issues/1304

**Comment by elena-zh** [comment]
Hey @terapi09 , could you please provide a bit more details about conditions and steps how to reproduce the issue? 
1. a wallet you connect
2. device, OS and a browser you use
3. steps you do before the app is crashed. 

Thanks in advance!
