### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by terapi09** [gnosis/cowswap#1304]
## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  },
  "OUTPUT": {
    "currencyId": "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  },
  "independentField": "INPUT",
  "typedValue": "100",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLSpanElement.removeChild (<anonymous>)
    at ks (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2497570)
    at Pu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2509382)
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2507340)
    at mu (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2503426)
    at https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452580
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2529999)
    at zi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452357)
    at Gi (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452525)
    at Ji (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2452460)
    at je (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2523809)
    at Qt (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:2431084)
    at HTMLElement.r (https://cowswap.exchange/static/js/4.25f80b54.chunk.js:2:4212159)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 8.1.0; VIA_A3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.159",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.159"
  },
  "os": {
    "name": "Android",
    "version": "8.1.0"
  },
  "device": {
    "model": "VIA_A3",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by terapi09** [comment]
0x933258bddd49beeca77f6d1889633c5429af45ea

**Comment by alfetopito** [comment]
@terapi09 are you still having issues?
We deployed a fix for the one you reported a few weeks ago.
Let us know if that's still not working for you
