### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by ialshjl** [gnosis/cowswap#1491]
## URL
  
https://cowswap.exchange/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
  },
  "OUTPUT": {
    "currencyId": "0x61CEAc48136d6782DBD83c09f51E23514D12470a"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:113999)
    at t.n.toFixed (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:73475)
    at ph (https://cowswap.exchange/static/js/main.3472693a.chunk.js:1:283921)
    at RC (https://cowswap.exchange/static/js/main.3472693a.chunk.js:1:429862)
    at ro (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2653786)
    at Ho (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2663353)
    at Gs (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2707235)
    at Su (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2693418)
    at Eu (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2693346)
    at Tu (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2693209)
    at mu (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2690175)
    at https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2639554
    at t.unstable_runWithPriority (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2716973)
    at zi (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2639331)
    at Ji (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2639499)
    at Gi (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2639434)
    at vu (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:2690496)
    at Object.notify (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:205708)
    at Object.notifyNestedSubs (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:206305)
    at i (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:206139)
    at d (https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:107290)
    at https://cowswap.exchange/static/js/main.3472693a.chunk.js:1:393834
    at https://cowswap.exchange/static/js/main.3472693a.chunk.js:1:392287
    at https://cowswap.exchange/static/js/4.2c699c4e.chunk.js:2:1409251
    at https://cowswap.exchange/static/js/main.3472693a.chunk.js:1:625502
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.82",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.82"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by elena-zh** [comment]
**Steps:** 

1. Open the app, connect a wallet in the Mainnet
2. Select token to sell - USDC
3. Select a token to buy - Subs (0x61CEAc48136d6782DBD83c09f51E23514D12470a)

**Comment by alfetopito** [comment]
The token Subs has `0` decimals https://etherscan.io/token/0x61CEAc48136d6782DBD83c09f51E23514D12470a

Likely the UI is not expecting that.

**Comment by W3stside** [comment]
![image](https://user-images.githubusercontent.com/21335563/135297986-4348a146-88d7-4c41-8f4d-80b483e03751.png)

1. check `formatMax` implementation when decimals === 0
2. check code before `formatMax` to handle 0 decimal tokens

**Comment by alfetopito** [comment]
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fdc%2Fef%2F92%2Fdcef92fee351e2dfbbf80338c3a17488.gif&f=1&nofb=1)

**Comment by alfetopito** [comment]
Pending release of the Hotfix https://github.com/gnosis/cowswap/pull/1497 as version 1.2.1
